# Generated by Django 5.1 on 2024-08-20 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_movementlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='action_type',
            field=models.CharField(choices=[('ADD', 'Adicionado'), ('REMOVE', 'Removido'), ('EDIT', 'Editado'), ('INCREASE', 'Aumentado'), ('DECREASE', 'Diminuído')], default='ADD', max_length=10),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
