# Generated by Django 5.1 on 2024-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_movementlog_observation_movementlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
